name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git checkout master
      - run: git remote add upstream https://${{secrets.GITHUB_TOKEN}}:x-oauth-basic@github.com/remaxjs/named-exports-db.git
      - run: git config --global user.email "yesmeck@gmail.com"
      - run: git config --global user.name "Wei Zhu"
      - run: npm version patch -m "Bump version [ci skip]"
      - run: git push upstream master --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
